"""
Risk Disclaimers
Standard disclaimers for the trading platform.
These should be displayed prominently to users.
"""

from typing import Dict, Any
from datetime import datetime


class Disclaimers:
    """Risk disclaimers for the trading platform"""

    # Short disclaimer for API responses
    SHORT_DISCLAIMER = (
        "This is not investment advice. Past performance does not guarantee future results. "
        "Please consult a SEBI-registered advisor before making investment decisions."
    )

    # Full disclaimer for UI display
    FULL_DISCLAIMER = """
IMPORTANT DISCLAIMER

1. NOT INVESTMENT ADVICE
The information provided by this application is for educational and informational purposes only.
It should not be construed as investment advice, financial advice, trading advice, or any other
sort of advice. You should not treat any of the application's content as such.

2. NO SEBI REGISTRATION
This application is NOT registered with the Securities and Exchange Board of India (SEBI).
The recommendations provided are generated by artificial intelligence algorithms and should
not be considered as advice from a registered investment advisor.

3. RISK WARNING
Trading in stocks and securities involves substantial risk of loss and is not suitable for
every investor. The valuation of stocks and securities may fluctuate, and as a result,
clients may lose more than their original investment.

4. PAST PERFORMANCE
Past performance is not indicative of future results. Any historical returns, expected returns,
or probability projections may not reflect actual future performance.

5. AI LIMITATIONS
The AI-powered recommendations are based on technical analysis and historical data.
They do not account for:
- Fundamental changes in company operations
- Macroeconomic factors
- Regulatory changes
- Insider information
- Black swan events

6. YOUR RESPONSIBILITY
Before making any investment decision, you should:
- Consult with a qualified financial advisor
- Conduct your own due diligence
- Consider your own financial situation and risk tolerance
- Never invest money you cannot afford to lose

7. NO WARRANTY
The application is provided "as is" without warranty of any kind. We do not guarantee
the accuracy, completeness, or usefulness of any information.

By using this application, you acknowledge that you have read and understood this disclaimer.
"""

    # Risk levels explanation
    RISK_LEVELS = {
        "high": {
            "label": "High Risk",
            "description": "Significant potential for loss. Only for experienced investors with high risk tolerance.",
            "icon": "🔴"
        },
        "medium": {
            "label": "Medium Risk",
            "description": "Moderate potential for both gains and losses. Suitable for balanced portfolios.",
            "icon": "🟡"
        },
        "low": {
            "label": "Low Risk",
            "description": "Lower potential for loss, but also limited upside. Suitable for conservative investors.",
            "icon": "🟢"
        }
    }

    # Confidence level warnings
    CONFIDENCE_WARNINGS = {
        "very_high": {
            "range": "85-100%",
            "message": "High confidence signals are rare. Verify with additional analysis.",
            "warning": False
        },
        "high": {
            "range": "70-84%",
            "message": "Good signal quality. Consider position sizing accordingly.",
            "warning": False
        },
        "medium": {
            "range": "55-69%",
            "message": "Mixed signals present. Use caution and smaller position sizes.",
            "warning": True
        },
        "low": {
            "range": "40-54%",
            "message": "Weak signal. Consider waiting for better opportunity.",
            "warning": True
        },
        "very_low": {
            "range": "Below 40%",
            "message": "Very uncertain. Not recommended for trading.",
            "warning": True
        }
    }

    @classmethod
    def get_api_disclaimer(cls) -> Dict[str, Any]:
        """Get disclaimer for API responses"""
        return {
            "disclaimer": cls.SHORT_DISCLAIMER,
            "is_investment_advice": False,
            "sebi_registered": False,
            "risk_warning": "Trading involves substantial risk of loss"
        }

    @classmethod
    def get_full_disclaimer(cls) -> Dict[str, Any]:
        """Get full disclaimer for UI display"""
        return {
            "short": cls.SHORT_DISCLAIMER,
            "full": cls.FULL_DISCLAIMER,
            "risk_levels": cls.RISK_LEVELS,
            "confidence_warnings": cls.CONFIDENCE_WARNINGS,
            "last_updated": "2024-01-01",
            "version": "1.0"
        }

    @classmethod
    def get_recommendation_disclaimer(
        cls,
        recommendation: str,
        confidence: float
    ) -> Dict[str, Any]:
        """Get specific disclaimer for a recommendation"""
        # Determine confidence level
        if confidence >= 85:
            conf_level = "very_high"
        elif confidence >= 70:
            conf_level = "high"
        elif confidence >= 55:
            conf_level = "medium"
        elif confidence >= 40:
            conf_level = "low"
        else:
            conf_level = "very_low"

        conf_warning = cls.CONFIDENCE_WARNINGS[conf_level]

        return {
            "recommendation": recommendation,
            "confidence": confidence,
            "confidence_level": conf_level,
            "confidence_warning": conf_warning["message"],
            "requires_caution": conf_warning["warning"],
            "disclaimer": cls.SHORT_DISCLAIMER,
            "action_reminder": (
                "Always verify with your own analysis and consult a financial advisor "
                "before making investment decisions."
            )
        }

    @classmethod
    def wrap_response(cls, response: Dict[str, Any]) -> Dict[str, Any]:
        """Wrap any API response with disclaimer"""
        response["_meta"] = {
            "disclaimer": cls.SHORT_DISCLAIMER,
            "timestamp": datetime.utcnow().isoformat(),
            "not_investment_advice": True
        }
        return response


# Convenience function
def add_disclaimer(response: Dict[str, Any]) -> Dict[str, Any]:
    """Add disclaimer to any response"""
    return Disclaimers.wrap_response(response)
